# Create an action to merge the translations from Crowdin to the main branch
name: Crowdin Auto Merge
on:
  pull_request:
    types:
      - labeled
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: { }
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: New Crowdin updates
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "New Crowdin updates"
          MERGE_METHOD: "merge"  # merge method to use (merge, squash, rebase)
          MERGE_FORKS: "false"  # allow merging PRs from forks
          MERGE_RETRIES: "1"  # number of times to retry merging
          MERGE_RETRY_SLEEP: "60"  # number of seconds to wait between retries
          MERGE_DELETE_BRANCH: "true"  # delete the branch after merging
          MERGE_COMMIT_MESSAGE: "Merged translations from Crowdin"  # commit message to use
          MERGE_PR_TITLE: "Merged translations from Crowdin"  # PR title to use
