name: Python Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace 'x' with the desired Python version

      - name: Install dependencies
        run: pip install -r requirements.txt  # Add any required dependencies to requirements.txt

      - name: Run Python script
        run: |
          python /trackers/parser.py  # Replace with the actual script name

      - name: Copy output file
        run: |
          cp trackers.xml ../..app/src/main/res/values/trackers.xml

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ../..app/src/main/res/values/trackers.xml
          git commit -m "Update trackers.xml"
